version: '3.8'

services:
  mysqldb:
    container_name: mysql-container
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: SkiStationDB
    ports:
      - "3307:3306"
    volumes:
      - ./volumes/mysqldb/mysqldb_data:/var/lib/mysql

  SkiStationProject:
    container_name: skicontainer
    build: .
    restart: on-failure
    image: skiapp
    ports:
      - "9090:9090"
    depends_on:
      - mysqldb

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
     - 8080:8080
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
       - ./jenkins_compose/jenkins_configuration:/var/jenkins_home

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
    restart: always
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2g -Xmx2g -XX:MaxDirectMemorySize=3g
      - NEXUS_SECURITY_RANDOMPASSWORD=true
    volumes:
      - ./volumes/nexus/nexus_data:/nexus-data
