version: '3.8'

services:
  mysqldb:
    container_name: mysql-container
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: SkiStationDB
    ports:
      - "3307:3306"
    volumes:
      - ./volumes/mysqldb/mysqldb_data:/var/lib/mysql

  SkiStationProject:
    container_name: skicontainer
    build: .
    restart: on-failure
    image: skiapp
    environment:
      spring.datasource.url: "jdbc:mysql://mysqldb:3306/SkiStationDB?createDatabaseIfNotExist=true"
      spring.datasource.username: root
      spring.datasource.password: password
    ports:
      - "9090:9090"
    depends_on:
      - mysqldb

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
     - 8080:8080
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
       - ./jenkins_compose/jenkins_configuration:/var/jenkins_home

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
      - "8085:8085"
    restart: always
    user: "1000:1000"
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2g -Xmx2g -XX:MaxDirectMemorySize=3g
      - NEXUS_SECURITY_RANDOMPASSWORD=true
    volumes:
      - ./volumes/nexus/nexus_data:/nexus-data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9099:9090"
    volumes:
      - ./volumes/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    depends_on:
      - jenkins
      - mysqldb

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "1000:1000"
    ports:
      - "3000:3000"
    links:
      - prometheus:prometheus
    volumes:
      - ./volumes/grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always



